### ISSUE TITLE
If statement 

### ISSUE THREAD

**Issue by mmd-osm** [gappleto97/overpassify#23]
This will be available in the next version: see https://github.com/drolbr/Overpass-API/commit/7bf3304e6995c5aecb5128b2cca1ca45e745afbc#diff-7fdff16d2c64c31f0fd49c5dc631b9bbR30

So there will be no need for the workaround. 

General hint: If you find missing stuff please open a feature request at Overpass API repo.

**Comment by LivInTheLookingGlass** [comment]
That'll be great to switch to when its live. Thanks!

For now I'll stick with the hacky way, because it will work in the meantime. I still need to get feature-parity before I can go back and change that sort of thing.

**Comment by mmd-osm** [comment]
btw: if you're looking for test cases, both http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example and http://dev.overpass-api.de/blog/ offer quite a good coverage of all features up to 0.7.54 and there's even more to come in 0.7.55.

**Comment by LivInTheLookingGlass** [comment]
While I have you here, could you glance at the file I just added? Its not totally fleshed out, but its a rough idea on how the object model gets translated to Python. I'm hoping you can point out if I have any obvious misunderstandings.

**Comment by mmd-osm** [comment]
Link to a test instance for `if( ... )` : http://overpass-turbo.eu/s/pWo

The example itself is a bit pointless but it lets you play around with the current implementation already.

**Comment by gappleto97** [comment]
Hi, just wanted to check on whether this has been implemented in the main version yet

**Comment by LivInTheLookingGlass** [comment]
Hi, I was just hoping to check when this is going to land on the main server. I don't really want to make any changes to my if statement logic unless I know it'll work for anyone who uses my library.

**Comment by mmd-osm** [comment]
I’d say some time around March 2018, maybe earlier.

**Comment by LivInTheLookingGlass** [comment]
Okay, thanks for the heads up. And while I have you, might I suggest using that as an excuse to add a while loop? It'd be nearly the exact same code and syntax.

**Comment by LivInTheLookingGlass** [comment]
This seems to be enabled on the main server, so I'll go ahead and add it this weekend. Should make the code this transpiler generates much more efficient.

@mmd-osm, what's the odds that we could also get a while loop? Or does accumulate largely do the same thing? I'm not entirely sure that I understand how that loop works.

**Comment by mmd-osm** [comment]
Right, `if `is available as a block statement now: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#The_block_statement_if

>  what's the odds that we could also get a while loop

Not sure, https://github.com/drolbr/Overpass-API/issues/456 is labeled as enhancement right now, which is better than a won't fix.
