### ISSUE TITLE
Ensure that typing concepts match up

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [gappleto97/overpassify#25]
I think there's a minor confusion on my part.

@mmd-osm, is a single node, for instance generated by node(1), also considered a set? Or do you need to explicitly construct it as such?

If it's the latter, then my object model is fundamentally wrong, and I have a better excuse to do a redesign.

**Comment by mmd-osm** [comment]
Yes, node(1) is also considered a set. Internally it all boils down to a c++ vector to store input sets  (one for each type, like node, way, rel, ...), where the number of elements doesn't matter. It could be empty, one or several elements.
